version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    container_name: poi_db
    ports:
      - "5432:5432"
    networks:
      - msnetwork
    environment:
      - POSTGRES_DB=poi_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./.data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "15432:8080"
    depends_on:
      - db
    networks:
      - msnetwork

networks:
  msnetwork:
    driver: bridge