# Server Port Configuration
server:
  port: 8080

#Application Name
spring:
  application:
    name: poi

# Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/poidb
    username: postgres
    password: root

# Hibernate Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect